/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sato_nativedemo_primitive_PrimitiveSample */

#ifndef _Included_sato_nativedemo_primitive_PrimitiveSample
#define _Included_sato_nativedemo_primitive_PrimitiveSample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sato_nativedemo_primitive_PrimitiveSample
 * Method:    booleanSample
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_sato_nativedemo_primitive_PrimitiveSample_booleanSample
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     sato_nativedemo_primitive_PrimitiveSample
 * Method:    byteSample
 * Signature: (B)B
 */
JNIEXPORT jbyte JNICALL Java_sato_nativedemo_primitive_PrimitiveSample_byteSample
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     sato_nativedemo_primitive_PrimitiveSample
 * Method:    charSample
 * Signature: (C)C
 */
JNIEXPORT jchar JNICALL Java_sato_nativedemo_primitive_PrimitiveSample_charSample
  (JNIEnv *, jobject, jchar);

/*
 * Class:     sato_nativedemo_primitive_PrimitiveSample
 * Method:    shortSample
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_sato_nativedemo_primitive_PrimitiveSample_shortSample
  (JNIEnv *, jobject, jshort);

/*
 * Class:     sato_nativedemo_primitive_PrimitiveSample
 * Method:    intSample
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_sato_nativedemo_primitive_PrimitiveSample_intSample
  (JNIEnv *, jobject, jint);

/*
 * Class:     sato_nativedemo_primitive_PrimitiveSample
 * Method:    longSample
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_sato_nativedemo_primitive_PrimitiveSample_longSample
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sato_nativedemo_primitive_PrimitiveSample
 * Method:    floatSample
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_sato_nativedemo_primitive_PrimitiveSample_floatSample
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     sato_nativedemo_primitive_PrimitiveSample
 * Method:    doubleSample
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_sato_nativedemo_primitive_PrimitiveSample_doubleSample
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     sato_nativedemo_primitive_PrimitiveSample
 * Method:    voidSample
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sato_nativedemo_primitive_PrimitiveSample_voidSample
  (JNIEnv *, jobject);

/*
 * Class:     sato_nativedemo_primitive_PrimitiveSample
 * Method:    stringSample
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sato_nativedemo_primitive_PrimitiveSample_stringSample
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
