/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sato_nativedemo_primitive_PrimitiveArraySample */

#ifndef _Included_sato_nativedemo_primitive_PrimitiveArraySample
#define _Included_sato_nativedemo_primitive_PrimitiveArraySample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sato_nativedemo_primitive_PrimitiveArraySample
 * Method:    booleanSample
 * Signature: ([Z)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_sato_nativedemo_primitive_PrimitiveArraySample_booleanSample
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     sato_nativedemo_primitive_PrimitiveArraySample
 * Method:    byteSample
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_sato_nativedemo_primitive_PrimitiveArraySample_byteSample
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     sato_nativedemo_primitive_PrimitiveArraySample
 * Method:    charSample
 * Signature: ([C)[C
 */
JNIEXPORT jcharArray JNICALL Java_sato_nativedemo_primitive_PrimitiveArraySample_charSample
  (JNIEnv *, jobject, jcharArray);

/*
 * Class:     sato_nativedemo_primitive_PrimitiveArraySample
 * Method:    shortSample
 * Signature: ([S)[S
 */
JNIEXPORT jshortArray JNICALL Java_sato_nativedemo_primitive_PrimitiveArraySample_shortSample
  (JNIEnv *, jobject, jshortArray);

/*
 * Class:     sato_nativedemo_primitive_PrimitiveArraySample
 * Method:    intSample
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_sato_nativedemo_primitive_PrimitiveArraySample_intSample
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     sato_nativedemo_primitive_PrimitiveArraySample
 * Method:    longSample
 * Signature: ([J)[J
 */
JNIEXPORT jlongArray JNICALL Java_sato_nativedemo_primitive_PrimitiveArraySample_longSample
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     sato_nativedemo_primitive_PrimitiveArraySample
 * Method:    floatSample
 * Signature: ([F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_sato_nativedemo_primitive_PrimitiveArraySample_floatSample
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     sato_nativedemo_primitive_PrimitiveArraySample
 * Method:    doubleSample
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_sato_nativedemo_primitive_PrimitiveArraySample_doubleSample
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     sato_nativedemo_primitive_PrimitiveArraySample
 * Method:    stringSample
 * Signature: ([Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_sato_nativedemo_primitive_PrimitiveArraySample_stringSample
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
